//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKyHocPhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class regist
    {
        public System.DateTime open_time { get; set; }
        public Nullable<System.DateTime> close_time { get; set; }
        public System.DateTime regist_time { get; set; }
        public string student_id { get; set; }
        public string subject_id { get; set; }
        public int table_core_id { get; set; }
    
        public virtual student student { get; set; }
        public virtual subject subject { get; set; }
        public virtual table_core table_core { get; set; }
    }
}
