//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKyHocPhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_core
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_core()
        {
            this.regist = new HashSet<regist>();
        }
    
        public int id { get; set; }
        public Nullable<double> average_core { get; set; }
        public Nullable<double> mid_core { get; set; }
        public Nullable<double> end_core { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regist> regist { get; set; }
    }
}
